/**
 * Gym Equipment Product Images Data
 * Auto-generated by optimize_gym_products.py — do not edit manually.
 * 104 images across 41 brands
 */

export interface EquipmentImage {
  brandSlug: string;
  brandName: string;
  equipmentSlug: string;
  equipmentName: string;
  src: string;
}

const ALL_EQUIPMENT_IMAGES: EquipmentImage[] = [
  { brandSlug: 'assault-fitness', brandName: "Assault Fitness", equipmentSlug: 'stationary-bike', equipmentName: 'Stationary Bike', src: '/equipment/assault-fitness/stationary-bike.webp' },
  { brandSlug: 'assault-fitness', brandName: "Assault Fitness", equipmentSlug: 'treadmill', equipmentName: 'Treadmill', src: '/equipment/assault-fitness/treadmill.webp' },
  { brandSlug: 'body-craft', brandName: "BodyCraft", equipmentSlug: 'stationary-bike', equipmentName: 'Stationary Bike', src: '/equipment/body-craft/stationary-bike.webp' },
  { brandSlug: 'body-craft', brandName: "BodyCraft", equipmentSlug: 'weight-machine', equipmentName: 'Weight Machine', src: '/equipment/body-craft/weight-machine.webp' },
  { brandSlug: 'body-solid', brandName: "Body-Solid", equipmentSlug: 'weight-machine', equipmentName: 'Weight Machine', src: '/equipment/body-solid/weight-machine.webp' },
  { brandSlug: 'bowflex', brandName: "Bowflex", equipmentSlug: 'elliptical', equipmentName: 'Elliptical', src: '/equipment/bowflex/elliptical.webp' },
  { brandSlug: 'bowflex', brandName: "Bowflex", equipmentSlug: 'rowing-machine', equipmentName: 'Rowing Machine', src: '/equipment/bowflex/rowing-machine.webp' },
  { brandSlug: 'bowflex', brandName: "Bowflex", equipmentSlug: 'stair-machine', equipmentName: 'Stair Machine', src: '/equipment/bowflex/stair-machine.webp' },
  { brandSlug: 'bowflex', brandName: "Bowflex", equipmentSlug: 'stationary-bike', equipmentName: 'Stationary Bike', src: '/equipment/bowflex/stationary-bike.webp' },
  { brandSlug: 'bowflex', brandName: "Bowflex", equipmentSlug: 'treadmill', equipmentName: 'Treadmill', src: '/equipment/bowflex/treadmill.webp' },
  { brandSlug: 'concept2', brandName: "Concept2", equipmentSlug: 'rowing-machine', equipmentName: 'Rowing Machine', src: '/equipment/concept2/rowing-machine.webp' },
  { brandSlug: 'cybex', brandName: "Cybex", equipmentSlug: 'elliptical', equipmentName: 'Elliptical', src: '/equipment/cybex/elliptical.webp' },
  { brandSlug: 'cybex', brandName: "Cybex", equipmentSlug: 'stair-machine', equipmentName: 'Stair Machine', src: '/equipment/cybex/stair-machine.webp' },
  { brandSlug: 'cybex', brandName: "Cybex", equipmentSlug: 'stationary-bike', equipmentName: 'Stationary Bike', src: '/equipment/cybex/stationary-bike.webp' },
  { brandSlug: 'cybex', brandName: "Cybex", equipmentSlug: 'treadmill', equipmentName: 'Treadmill', src: '/equipment/cybex/treadmill.webp' },
  { brandSlug: 'cybex', brandName: "Cybex", equipmentSlug: 'weight-machine', equipmentName: 'Weight Machine', src: '/equipment/cybex/weight-machine.webp' },
  { brandSlug: 'diamondback', brandName: "Diamondback", equipmentSlug: 'elliptical', equipmentName: 'Elliptical', src: '/equipment/diamondback/elliptical.webp' },
  { brandSlug: 'diamondback', brandName: "Diamondback", equipmentSlug: 'stationary-bike', equipmentName: 'Stationary Bike', src: '/equipment/diamondback/stationary-bike.webp' },
  { brandSlug: 'echelon', brandName: "Echelon", equipmentSlug: 'stationary-bike', equipmentName: 'Stationary Bike', src: '/equipment/echelon/stationary-bike.webp' },
  { brandSlug: 'fitness-gear', brandName: "Fitness Gear", equipmentSlug: 'weight-machine', equipmentName: 'Weight Machine', src: '/equipment/fitness-gear/weight-machine.webp' },
  { brandSlug: 'freemotion', brandName: "FreeMotion", equipmentSlug: 'elliptical', equipmentName: 'Elliptical', src: '/equipment/freemotion/elliptical.webp' },
  { brandSlug: 'freemotion', brandName: "FreeMotion", equipmentSlug: 'treadmill', equipmentName: 'Treadmill', src: '/equipment/freemotion/treadmill.webp' },
  { brandSlug: 'freemotion', brandName: "FreeMotion", equipmentSlug: 'weight-machine', equipmentName: 'Weight Machine', src: '/equipment/freemotion/weight-machine.webp' },
  { brandSlug: 'hammer-strength', brandName: "Hammer Strength", equipmentSlug: 'weight-machine', equipmentName: 'Weight Machine', src: '/equipment/hammer-strength/weight-machine.webp' },
  { brandSlug: 'hoist', brandName: "Hoist", equipmentSlug: 'weight-machine', equipmentName: 'Weight Machine', src: '/equipment/hoist/weight-machine.webp' },
  { brandSlug: 'horizon', brandName: "Horizon", equipmentSlug: 'elliptical', equipmentName: 'Elliptical', src: '/equipment/horizon/elliptical.webp' },
  { brandSlug: 'horizon', brandName: "Horizon", equipmentSlug: 'stationary-bike', equipmentName: 'Stationary Bike', src: '/equipment/horizon/stationary-bike.webp' },
  { brandSlug: 'horizon', brandName: "Horizon", equipmentSlug: 'treadmill', equipmentName: 'Treadmill', src: '/equipment/horizon/treadmill.webp' },
  { brandSlug: 'hydrow', brandName: "Hydrow", equipmentSlug: 'rowing-machine', equipmentName: 'Rowing Machine', src: '/equipment/hydrow/rowing-machine.webp' },
  { brandSlug: 'inspire', brandName: "Inspire Fitness", equipmentSlug: 'weight-machine', equipmentName: 'Weight Machine', src: '/equipment/inspire/weight-machine.webp' },
  { brandSlug: 'ironman', brandName: "IRONMAN", equipmentSlug: 'treadmill', equipmentName: 'Treadmill', src: '/equipment/ironman/treadmill.webp' },
  { brandSlug: 'keiser', brandName: "Keiser", equipmentSlug: 'stationary-bike', equipmentName: 'Stationary Bike', src: '/equipment/keiser/stationary-bike.webp' },
  { brandSlug: 'landice', brandName: "Landice", equipmentSlug: 'treadmill', equipmentName: 'Treadmill', src: '/equipment/landice/treadmill.webp' },
  { brandSlug: 'legend-fitness', brandName: "Legend Fitness", equipmentSlug: 'weight-machine', equipmentName: 'Weight Machine', src: '/equipment/legend-fitness/weight-machine.webp' },
  { brandSlug: 'life-fitness', brandName: "Life Fitness", equipmentSlug: 'elliptical', equipmentName: 'Elliptical', src: '/equipment/life-fitness/elliptical.webp' },
  { brandSlug: 'life-fitness', brandName: "Life Fitness", equipmentSlug: 'rowing-machine', equipmentName: 'Rowing Machine', src: '/equipment/life-fitness/rowing-machine.webp' },
  { brandSlug: 'life-fitness', brandName: "Life Fitness", equipmentSlug: 'stair-machine', equipmentName: 'Stair Machine', src: '/equipment/life-fitness/stair-machine.webp' },
  { brandSlug: 'life-fitness', brandName: "Life Fitness", equipmentSlug: 'stationary-bike', equipmentName: 'Stationary Bike', src: '/equipment/life-fitness/stationary-bike.webp' },
  { brandSlug: 'life-fitness', brandName: "Life Fitness", equipmentSlug: 'treadmill', equipmentName: 'Treadmill', src: '/equipment/life-fitness/treadmill.webp' },
  { brandSlug: 'life-fitness', brandName: "Life Fitness", equipmentSlug: 'weight-machine', equipmentName: 'Weight Machine', src: '/equipment/life-fitness/weight-machine.webp' },
  { brandSlug: 'marcy', brandName: "Marcy", equipmentSlug: 'weight-machine', equipmentName: 'Weight Machine', src: '/equipment/marcy/weight-machine.webp' },
  { brandSlug: 'matrix', brandName: "Matrix", equipmentSlug: 'elliptical', equipmentName: 'Elliptical', src: '/equipment/matrix/elliptical.webp' },
  { brandSlug: 'matrix', brandName: "Matrix", equipmentSlug: 'rowing-machine', equipmentName: 'Rowing Machine', src: '/equipment/matrix/rowing-machine.webp' },
  { brandSlug: 'matrix', brandName: "Matrix", equipmentSlug: 'stair-machine', equipmentName: 'Stair Machine', src: '/equipment/matrix/stair-machine.webp' },
  { brandSlug: 'matrix', brandName: "Matrix", equipmentSlug: 'stationary-bike', equipmentName: 'Stationary Bike', src: '/equipment/matrix/stationary-bike.webp' },
  { brandSlug: 'matrix', brandName: "Matrix", equipmentSlug: 'treadmill', equipmentName: 'Treadmill', src: '/equipment/matrix/treadmill.webp' },
  { brandSlug: 'matrix', brandName: "Matrix", equipmentSlug: 'weight-machine', equipmentName: 'Weight Machine', src: '/equipment/matrix/weight-machine.webp' },
  { brandSlug: 'nautilus', brandName: "Nautilus", equipmentSlug: 'stair-machine', equipmentName: 'Stair Machine', src: '/equipment/nautilus/stair-machine.webp' },
  { brandSlug: 'nautilus', brandName: "Nautilus", equipmentSlug: 'stationary-bike', equipmentName: 'Stationary Bike', src: '/equipment/nautilus/stationary-bike.webp' },
  { brandSlug: 'nautilus', brandName: "Nautilus", equipmentSlug: 'weight-machine', equipmentName: 'Weight Machine', src: '/equipment/nautilus/weight-machine.webp' },
  { brandSlug: 'nordictrack', brandName: "NordicTrack", equipmentSlug: 'elliptical', equipmentName: 'Elliptical', src: '/equipment/nordictrack/elliptical.webp' },
  { brandSlug: 'nordictrack', brandName: "NordicTrack", equipmentSlug: 'rowing-machine', equipmentName: 'Rowing Machine', src: '/equipment/nordictrack/rowing-machine.webp' },
  { brandSlug: 'nordictrack', brandName: "NordicTrack", equipmentSlug: 'stair-machine', equipmentName: 'Stair Machine', src: '/equipment/nordictrack/stair-machine.webp' },
  { brandSlug: 'nordictrack', brandName: "NordicTrack", equipmentSlug: 'stationary-bike', equipmentName: 'Stationary Bike', src: '/equipment/nordictrack/stationary-bike.webp' },
  { brandSlug: 'nordictrack', brandName: "NordicTrack", equipmentSlug: 'treadmill', equipmentName: 'Treadmill', src: '/equipment/nordictrack/treadmill.webp' },
  { brandSlug: 'octane', brandName: "Octane Fitness", equipmentSlug: 'elliptical', equipmentName: 'Elliptical', src: '/equipment/octane/elliptical.webp' },
  { brandSlug: 'octane', brandName: "Octane Fitness", equipmentSlug: 'rowing-machine', equipmentName: 'Rowing Machine', src: '/equipment/octane/rowing-machine.webp' },
  { brandSlug: 'peloton', brandName: "Peloton", equipmentSlug: 'stationary-bike', equipmentName: 'Stationary Bike', src: '/equipment/peloton/stationary-bike.webp' },
  { brandSlug: 'peloton', brandName: "Peloton", equipmentSlug: 'treadmill', equipmentName: 'Treadmill', src: '/equipment/peloton/treadmill.webp' },
  { brandSlug: 'powertec', brandName: "Powertec", equipmentSlug: 'weight-machine', equipmentName: 'Weight Machine', src: '/equipment/powertec/weight-machine.webp' },
  { brandSlug: 'precor', brandName: "Precor", equipmentSlug: 'elliptical', equipmentName: 'Elliptical', src: '/equipment/precor/elliptical.webp' },
  { brandSlug: 'precor', brandName: "Precor", equipmentSlug: 'stair-machine', equipmentName: 'Stair Machine', src: '/equipment/precor/stair-machine.webp' },
  { brandSlug: 'precor', brandName: "Precor", equipmentSlug: 'stationary-bike', equipmentName: 'Stationary Bike', src: '/equipment/precor/stationary-bike.webp' },
  { brandSlug: 'precor', brandName: "Precor", equipmentSlug: 'treadmill', equipmentName: 'Treadmill', src: '/equipment/precor/treadmill.webp' },
  { brandSlug: 'precor', brandName: "Precor", equipmentSlug: 'weight-machine', equipmentName: 'Weight Machine', src: '/equipment/precor/weight-machine.webp' },
  { brandSlug: 'proform', brandName: "ProForm", equipmentSlug: 'elliptical', equipmentName: 'Elliptical', src: '/equipment/proform/elliptical.webp' },
  { brandSlug: 'proform', brandName: "ProForm", equipmentSlug: 'stationary-bike', equipmentName: 'Stationary Bike', src: '/equipment/proform/stationary-bike.webp' },
  { brandSlug: 'proform', brandName: "ProForm", equipmentSlug: 'treadmill', equipmentName: 'Treadmill', src: '/equipment/proform/treadmill.webp' },
  { brandSlug: 'rogue', brandName: "Rogue Fitness", equipmentSlug: 'weight-machine', equipmentName: 'Weight Machine', src: '/equipment/rogue/weight-machine.webp' },
  { brandSlug: 'schwinn', brandName: "Schwinn", equipmentSlug: 'elliptical', equipmentName: 'Elliptical', src: '/equipment/schwinn/elliptical.webp' },
  { brandSlug: 'schwinn', brandName: "Schwinn", equipmentSlug: 'stationary-bike', equipmentName: 'Stationary Bike', src: '/equipment/schwinn/stationary-bike.webp' },
  { brandSlug: 'sole', brandName: "Sole", equipmentSlug: 'elliptical', equipmentName: 'Elliptical', src: '/equipment/sole/elliptical.webp' },
  { brandSlug: 'sole', brandName: "Sole", equipmentSlug: 'stationary-bike', equipmentName: 'Stationary Bike', src: '/equipment/sole/stationary-bike.webp' },
  { brandSlug: 'sole', brandName: "Sole", equipmentSlug: 'treadmill', equipmentName: 'Treadmill', src: '/equipment/sole/treadmill.webp' },
  { brandSlug: 'spirit', brandName: "Spirit Fitness", equipmentSlug: 'elliptical', equipmentName: 'Elliptical', src: '/equipment/spirit/elliptical.webp' },
  { brandSlug: 'spirit', brandName: "Spirit Fitness", equipmentSlug: 'rowing-machine', equipmentName: 'Rowing Machine', src: '/equipment/spirit/rowing-machine.webp' },
  { brandSlug: 'spirit', brandName: "Spirit Fitness", equipmentSlug: 'stair-machine', equipmentName: 'Stair Machine', src: '/equipment/spirit/stair-machine.webp' },
  { brandSlug: 'spirit', brandName: "Spirit Fitness", equipmentSlug: 'stationary-bike', equipmentName: 'Stationary Bike', src: '/equipment/spirit/stationary-bike.webp' },
  { brandSlug: 'spirit', brandName: "Spirit Fitness", equipmentSlug: 'treadmill', equipmentName: 'Treadmill', src: '/equipment/spirit/treadmill.webp' },
  { brandSlug: 'spirit', brandName: "Spirit Fitness", equipmentSlug: 'weight-machine', equipmentName: 'Weight Machine', src: '/equipment/spirit/weight-machine.webp' },
  { brandSlug: 'stairmaster', brandName: "StairMaster", equipmentSlug: 'stair-machine', equipmentName: 'Stair Machine', src: '/equipment/stairmaster/stair-machine.webp' },
  { brandSlug: 'star-trac', brandName: "Star Trac", equipmentSlug: 'treadmill', equipmentName: 'Treadmill', src: '/equipment/star-trac/treadmill.webp' },
  { brandSlug: 'star-trac', brandName: "Star Trac", equipmentSlug: 'weight-machine', equipmentName: 'Weight Machine', src: '/equipment/star-trac/weight-machine.webp' },
  { brandSlug: 'sunny-health', brandName: "Sunny Health & Fitness", equipmentSlug: 'elliptical', equipmentName: 'Elliptical', src: '/equipment/sunny-health/elliptical.webp' },
  { brandSlug: 'sunny-health', brandName: "Sunny Health & Fitness", equipmentSlug: 'rowing-machine', equipmentName: 'Rowing Machine', src: '/equipment/sunny-health/rowing-machine.webp' },
  { brandSlug: 'sunny-health', brandName: "Sunny Health & Fitness", equipmentSlug: 'stationary-bike', equipmentName: 'Stationary Bike', src: '/equipment/sunny-health/stationary-bike.webp' },
  { brandSlug: 'sunny-health', brandName: "Sunny Health & Fitness", equipmentSlug: 'treadmill', equipmentName: 'Treadmill', src: '/equipment/sunny-health/treadmill.webp' },
  { brandSlug: 'technogym', brandName: "Technogym", equipmentSlug: 'elliptical', equipmentName: 'Elliptical', src: '/equipment/technogym/elliptical.webp' },
  { brandSlug: 'technogym', brandName: "Technogym", equipmentSlug: 'rowing-machine', equipmentName: 'Rowing Machine', src: '/equipment/technogym/rowing-machine.webp' },
  { brandSlug: 'technogym', brandName: "Technogym", equipmentSlug: 'stair-machine', equipmentName: 'Stair Machine', src: '/equipment/technogym/stair-machine.webp' },
  { brandSlug: 'technogym', brandName: "Technogym", equipmentSlug: 'stationary-bike', equipmentName: 'Stationary Bike', src: '/equipment/technogym/stationary-bike.webp' },
  { brandSlug: 'technogym', brandName: "Technogym", equipmentSlug: 'treadmill', equipmentName: 'Treadmill', src: '/equipment/technogym/treadmill.webp' },
  { brandSlug: 'technogym', brandName: "Technogym", equipmentSlug: 'weight-machine', equipmentName: 'Weight Machine', src: '/equipment/technogym/weight-machine.webp' },
  { brandSlug: 'titan-fitness', brandName: "Titan Fitness", equipmentSlug: 'weight-machine', equipmentName: 'Weight Machine', src: '/equipment/titan-fitness/weight-machine.webp' },
  { brandSlug: 'true-fitness', brandName: "TRUE Fitness", equipmentSlug: 'elliptical', equipmentName: 'Elliptical', src: '/equipment/true-fitness/elliptical.webp' },
  { brandSlug: 'true-fitness', brandName: "TRUE Fitness", equipmentSlug: 'rowing-machine', equipmentName: 'Rowing Machine', src: '/equipment/true-fitness/rowing-machine.webp' },
  { brandSlug: 'true-fitness', brandName: "TRUE Fitness", equipmentSlug: 'stair-machine', equipmentName: 'Stair Machine', src: '/equipment/true-fitness/stair-machine.webp' },
  { brandSlug: 'true-fitness', brandName: "TRUE Fitness", equipmentSlug: 'stationary-bike', equipmentName: 'Stationary Bike', src: '/equipment/true-fitness/stationary-bike.webp' },
  { brandSlug: 'true-fitness', brandName: "TRUE Fitness", equipmentSlug: 'treadmill', equipmentName: 'Treadmill', src: '/equipment/true-fitness/treadmill.webp' },
  { brandSlug: 'true-fitness', brandName: "TRUE Fitness", equipmentSlug: 'weight-machine', equipmentName: 'Weight Machine', src: '/equipment/true-fitness/weight-machine.webp' },
  { brandSlug: 'waterrower', brandName: "WaterRower", equipmentSlug: 'rowing-machine', equipmentName: 'Rowing Machine', src: '/equipment/waterrower/rowing-machine.webp' },
  { brandSlug: 'xterra', brandName: "XTERRA", equipmentSlug: 'elliptical', equipmentName: 'Elliptical', src: '/equipment/xterra/elliptical.webp' },
  { brandSlug: 'xterra', brandName: "XTERRA", equipmentSlug: 'rowing-machine', equipmentName: 'Rowing Machine', src: '/equipment/xterra/rowing-machine.webp' },
  { brandSlug: 'xterra', brandName: "XTERRA", equipmentSlug: 'treadmill', equipmentName: 'Treadmill', src: '/equipment/xterra/treadmill.webp' },
];

/** Get a specific product image for a brand + equipment combination */
export function getEquipmentImage(brandSlug: string, equipmentSlug: string): EquipmentImage | undefined {
  return ALL_EQUIPMENT_IMAGES.find(
    img => img.brandSlug === brandSlug && img.equipmentSlug === equipmentSlug
  );
}

/** Get all product images for a specific brand */
export function getEquipmentImagesForBrand(brandSlug: string): EquipmentImage[] {
  return ALL_EQUIPMENT_IMAGES.filter(img => img.brandSlug === brandSlug);
}

/** Get all brand product images for a specific equipment type */
export function getEquipmentImagesForType(equipmentSlug: string): EquipmentImage[] {
  return ALL_EQUIPMENT_IMAGES.filter(img => img.equipmentSlug === equipmentSlug);
}

/** Get all equipment images */
export function getAllEquipmentImages(): EquipmentImage[] {
  return ALL_EQUIPMENT_IMAGES;
}
